from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 210)
        Dialog.setMaximumSize(QtCore.QSize(530, 210))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("cap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.labelTitle = QtGui.QLabel(Dialog)
        self.labelTitle.setGeometry(QtCore.QRect(20, 10, 491, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(25)
        font.setWeight(75)
        font.setBold(True)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 518, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelProv = QtGui.QLabel(self.layoutWidget)
        self.labelProv.setObjectName("labelProv")
        self.horizontalLayout.addWidget(self.labelProv)
        self.lineProv = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineProv.sizePolicy().hasHeightForWidth())
        self.lineProv.setSizePolicy(sizePolicy)
        self.lineProv.setMinimumSize(QtCore.QSize(0, 25))
        self.lineProv.setMaximumSize(QtCore.QSize(51, 16777215))
        self.lineProv.setObjectName("lineProv")
        self.horizontalLayout.addWidget(self.lineProv)
        self.labelLocal = QtGui.QLabel(self.layoutWidget)
        self.labelLocal.setObjectName("labelLocal")
        self.horizontalLayout.addWidget(self.labelLocal)
        self.lineLocal = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineLocal.sizePolicy().hasHeightForWidth())
        self.lineLocal.setSizePolicy(sizePolicy)
        self.lineLocal.setMinimumSize(QtCore.QSize(0, 25))
        self.lineLocal.setObjectName("lineLocal")
        self.horizontalLayout.addWidget(self.lineLocal)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelComune = QtGui.QLabel(self.layoutWidget)
        self.labelComune.setObjectName("labelComune")
        self.horizontalLayout_2.addWidget(self.labelComune)
        self.lineComune = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineComune.sizePolicy().hasHeightForWidth())
        self.lineComune.setSizePolicy(sizePolicy)
        self.lineComune.setMinimumSize(QtCore.QSize(0, 25))
        self.lineComune.setObjectName("lineComune")
        self.horizontalLayout_2.addWidget(self.lineComune)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.buttonCerca = QtGui.QPushButton(self.layoutWidget)
        self.buttonCerca.setMinimumSize(QtCore.QSize(200, 23))
        self.buttonCerca.setObjectName("buttonCerca")
        self.horizontalLayout_4.addWidget(self.buttonCerca)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonExit = QtGui.QPushButton(self.layoutWidget)
        self.buttonExit.setObjectName("buttonExit")
        self.horizontalLayout_3.addWidget(self.buttonExit)
        self.labelCap = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCap.sizePolicy().hasHeightForWidth())
        self.labelCap.setSizePolicy(sizePolicy)
        self.labelCap.setObjectName("labelCap")
        self.horizontalLayout_3.addWidget(self.labelCap)
        self.lineCap = QtGui.QLineEdit(self.layoutWidget)
        self.lineCap.setMinimumSize(QtCore.QSize(0, 25))
        self.lineCap.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setWeight(75)
        font.setBold(True)
        self.lineCap.setFont(font)
        self.lineCap.setObjectName("lineCap")
        self.horizontalLayout_3.addWidget(self.lineCap)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Reve Cap Search", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTitle.setText(QtGui.QApplication.translate("Dialog", "Reve Cap Search", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProv.setText(QtGui.QApplication.translate("Dialog", "Provincia:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLocal.setText(QtGui.QApplication.translate("Dialog", "Località:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelComune.setText(QtGui.QApplication.translate("Dialog", "Comune: ", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonCerca.setText(QtGui.QApplication.translate("Dialog", "Cerca", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonExit.setText(QtGui.QApplication.translate("Dialog", "Esci", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCap.setText(QtGui.QApplication.translate("Dialog", "                                                                   CAP:", None, QtGui.QApplication.UnicodeUTF8))

